name: Update repository

on:
  push:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build-void:
    name: Build Void Linux packages
    uses: ./.github/workflows/build-void.yml
    secrets: inherit

  deploy:
    name: Deploy everything to Netlify
    if: github.ref == 'refs/heads/main'
    needs:
      - build-void
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
